apiVersion: v1
kind: Pod
metadata:
    name: badri-prod-deploy
    labels:
      app: badri-prod
spec:
      containers:
        - name: badri-container
          image: 9743625/badri:2.0
          ports:
          - containerPort: 8080
