apiVersion:  v1
kind: Service
metadata:
    name: nodeport-service
spec:
    type: NodePort
    selector:
       app: badri-pod-template
    ports:
     - nodePort: 30090
       port: 80
       targetPort: 80
