apiVersion:  v1
kind: Service
metadata:
    name: nodeport-service
spec:
    type: NodePort
    selector:
       app: badri-prod
    ports:
     - nodePort: 30090
       port: 8080
       targetPort: 8080
